---
kind: pipeline
name: build

workspace:
  base: /go
  path: src/github.com/sakti/prviewer

steps:
  - name: build
    image: golang:1.11
    environment:
      GO111MODULE: on
    commands: 
    - apt-get update
    - apt-get install -y libgtk-3-dev
    - go mod download
    - sh .drone.sh